version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.telegram:telegrambots
    versions:
    - 5.0.1.1
  - dependency-name: org.springframework.statemachine:spring-statemachine-core
    versions:
    - 2.4.0
  - dependency-name: com.github.ozsie:detekt-maven-plugin
    versions:
    - 1.15.0.1
  - dependency-name: org.apache.maven.wagon:wagon-ftp
    versions:
    - 3.4.2
  - dependency-name: org.zalando:jackson-datatype-money
    versions:
    - 1.2.1
