= {project-name} Documentation
Systemkern <office@systemkern.com>
VERSION, {localdate} {localtime}
:doctype: book
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: github
:toc: left
:toclevels: 4
:sectlinks:
:sectnums:

= Application Start
To start {project-name} open your Unix shell or Windows command prompt, navigate to the {project-name} application
directory and type or copy the following command:

[subs="attributes+"]
```
java -jar {final-name}.jar
```


== Configuration and Startup
The application is configured via two different configuration files. The Technical `application.properties` and
the business oriented `application.yml`. The configuration for the so called default profile is called "application.yml".
This is most likely the only configuration file that you will need to modify.

== Multiple execution profiles
This application supports multiple profiles which can be activated during startup.
They are configured in separate configuration files which are named `application-PROFILENAME.yml`.
If you want to use a profile called "myprofile2" you make a copy of application.yml named `application-myprofile2.yml` and start the application as follows:
[subs="attributes+"]
```
java -jar {final-name}.jar --spring.profiles.active=myprofile2
```
For more information please refer to the https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html#howto-set-active-spring-profiles[Spring Boot Documentation].


= API Requests
== Additional API Requests

=== Echo
Echo is a sample post request which returns exactly the same object as the one provided.
It can be used to test Json Object mapper implementations

operation::echo[snippets='curl-request,http-request,http-response,response-fields']

=== Ping
As simple ping signal which returns the current system timestamp

operation::ping[snippets='curl-request,http-request,http-response,response-fields']

=== User
User is a module created to answer CRUD(Create,read,update and delete) requests,
it does not always return a json, but a Http code that show if was successful.
Next examples of http requests and responses are exposed

==== Create
To work with creation of users, a post request is needed. It's body should contain the following
data: "name" and "password".

operation::user_create[snippets='curl-request,http-request,http-response']

==== Read
To read users is not required body, just the "id" which is sent by GET http verb. This "id" should
be in the URL at the end.

operation::user_read[snippets='curl-request,http-request,http-response,response-fields']

==== Update
To update an user, the url is equal to the Read case. The difference is in the verb which is
PUT http, and the body of the request should contain the new values of "name" and "password".

operation::user_update[snippets='curl-request,http-request,http-response']

==== Delete
To delete an user is required it's "id" and the http verb is DELETE. The URL is equal to Read
case.

operation::user_delete[snippets='curl-request,http-request,http-response']